version: "3.2"
services:
  service-user:
    build: ./service-user
    ports:
      - "6650:6650"
  service-order:
    build: ./service-order
    ports:
      - "6660:6660"
  gateway:
    build: ./gateway
    ports:
      - "6620:6620"