server:
  port: 9550
spring:
  application:
    name: cloud-web
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.20:8849
        namespace: develop
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.137.20:8086
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.137.20:8849
            namespace: develop
            dataId: service-goods-flow-rules
            data-type: json
            rule-type: flow
dubbo:
  application:
    name: ${spring.application.name}
    register-consumer: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.137.20:8849
  cloud:
    subscribed-services: service-user
  consumer:
    check: false