server:
  port: 9550
spring:
  application:
    name: cloud-web
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: develop
        group: micro_config
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: develop
        group: micro_service
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8868
        port: 8739
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            group: micro_sentinel
            dataId: cloud-web-flow-rules
            data-type: json
            rule-type: flow
dubbo:
  application:
    name: ${spring.application.name}
    register-consumer: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    parameters: { namespace: develop, group: micro_dubbo }
  cloud:
    subscribed-services: service-user
  consumer:
    check: false