server:
  port: 6710
spring:
  application:
    name: elastic-search
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.11:3306/hotel?serverTimezone=GMT%2B8
    username: root
    password: ban
mybatis-plus:
  type-aliases-package: com.ban.entity
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
