version: "3.2"
services:
  userservice:
    build: ./user
    ports:
      - "6650:6650"
  orderservice:
    build: ./order
    ports:
      - "6660:6660"
  gateway:
    build: ./gateway
    ports:
      - "6620:6620"