server:
  port: 9550
spring:
  application:
    name: cloud-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: develop
        group: micro_service
        register-enabled: false
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8868
        port: 8739
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            dataId: ${spring.application.name}-flow-rules
            groupId: micro_sentinel
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            dataId: ${spring.application.name}-degrade-rules
            groupId: micro_sentinel
            data-type: json
            rule-type: degrade
        system:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            dataId: ${spring.application.name}-system-rules
            groupId: micro_sentinel
            data-type: json
            rule-type: system
        authority:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            dataId: ${spring.application.name}-authority-rules
            groupId: micro_sentinel
            data-type: json
            rule-type: authority
        param-flow:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: develop
            dataId: ${spring.application.name}-param-flow-rules
            groupId: micro_sentinel
            data-type: json
            rule-type: param-flow
dubbo:
  application:
    name: ${spring.application.name}
    register-consumer: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    parameters: { namespace: develop, group: micro_dubbo }
    use-as-config-center: false
    use-as-metadata-center: false
  cloud:
    subscribed-services: service-user
  consumer:
    check: false