server:
  port: 8820
spring:
  application:
    name: itcast_gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Method=GET
            - Host=127.0.0.1
            - Path=/user/**
        - id: order_service
          uri: lb://order-service
          predicates:
            - Path=/order/**
